[package]
name = "cross-authenticode"
version = "0.0.0"
edition = "2024"
description = "Cross-platform XDG Base Directory Specification implementation"
license = "MIT OR Apache-2.0"
repository = "https://github.com/secana/cross-authenticode"
readme = "README.md"
keywords = ["authenticode", "certificate", "pefile"]
authors = ["Stefan Hausotte"]
documentation = "https://docs.rs/cross-authenticode"

[dependencies]
cms = "0.2"
rust-crypto = "0.2"
thiserror = "2.0"
object = "0.36"
